project_name: kubectl-jq
env_files:
    github_token: ~/.github_token
before:
    hooks:
        - go test ./...
        - golangci-lint run
builds:
    - id: kubectl-jq
      dir: .
      main: ./cmd/kubectl-jq/main.go
      binary: kubectl-jq
      env:
          - CGO_ENABLED=0
      goos:
          - linux
          - windows
          - darwin
      goarch:
          - amd64
          - arm
          - arm64
      goarm:
          - 6
          - 7
      goamd64:
          - v2
          - v3
      ignore:
          - goos: darwin
            goarch: arm
          - goos: windows
            goarch: arm
          - goos: windows
            goarch: arm64
      ldflags:
          - "-s -w -X main.version=v{{.Version}} -X main.commit={{.Commit}} -X
            main.date={{.CommitDate}} -X main.builtBy=goreleaser"
      mod_timestamp: "{{.CommitTimestamp}}"
      flags: -trimpath
archives:
    - id: kubectl-jq
      builds:
          - kubectl-jq
      format: binary
      wrap_in_directory: false
      name_template: |-
          kubectl-jq_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v2") }}{{ .Amd64 }}{{ end }}
checksum:
    name_template: "checksums.txt"
snapshot:
    name_template: "{{ slice .Tag }}-next"
changelog:
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"
            - "^goreleaser:"
            - "^README:"
release:
    github:
        owner: jrockway
        name: kubectl-jq
    ids:
        - kubectl-jq
    draft: true
    prerelease: auto
    name_template: "kubectl-jq v{{.Version}}"
    disable: false
source:
    enabled: false
brews:
    - name: kubectl-jq
      tap:
          owner: jrockway
          name: homebrew-tap
      homepage: "https://github.com/jrockway/kubectl-jq"
      description: "Query Kubernetes objects with JQ"
      license: Apache-2.0
      goarm: 6
      goamd64: v2
      test: |
          system "#{bin}/kubectl-jq --help"
